version: '3'
services:
  strapi:
    build: .
    container_name: salazar_server
    environment:
      NODE_ENV: ${NODE_ENV}
      DATABASE_CLIENT: ${DATABASE_CLIENT}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_SSL: ${DATABASE_SSL}
      DATABASE_SRV: ${DATABASE_SRV}
      CORS_ORIGIN: ${CORS_ORIGIN}
      ADMIN_JWT_SECRET: ${ADMIN_JWT_SECRET}
    ports:
      - '1337:1337'