version: '3'
services:
  strapi:
    build: .
    environment:
      # Using Variable Subtitution to obtain environment variables. For more : https://docs.docker.com/compose/compose-file/compose-file-v3/#variable-substitution.
      NODE_ENV: ${NODE_ENV}
      # == MongoDB Atlas configuration ==
      DATABASE_CLIENT: mongo
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_SRV: ${DATABASE_SRV}
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_SSL: ${DATABASE_SSL}
      # AUTHENTICATION_DATABASE: admin
      CORS_ORIGIN: ${CORS_ORIGIN}
      ADMIN_JWT_SECRET: ${ADMIN_JWT_SECRET}
      # == Cloudinary configuration ==
      CLOUDINARY_NAME: ${CLOUDINARY_NAME}
      CLOUDINARY_KEY: ${CLOUDINARY_KEY}
      CLOUDINARY_SECRET: ${CLOUDINARY_SECRET}
    ports:
      - '1337:1337'